# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);



GET http://localhost:8080/electricity/api/author/1
Accept: application/json

###

//method for search author by his name and surname
POST http://localhost:8080/electricity/api/author/auth
Content-Type: application/json

{"name": "Nikolas", "surname": "Tesla"}

###


POST http://localhost:8080/electricity/api/author/save
Content-Type: application/json

{"name": "Arturas",  "surname": "Kaseta"}

###

DELETE http://localhost:8080/electricity/api/author/delete/6
Content-Type: application/json

###


PUT http://localhost:8080/electricity/api/author/update/7
Content-Type: application/json

{"name": "Kazimieras", "surname": "Fontanas"}

###

//parameters as QueryParam
GET http://localhost:8080/electricity/api/author/list?size=3&skip=2
Accept: application/json

###

//parameters as PathParam
GET http://localhost:8080/electricity/api/author/list/3/2
Accept: application/json

###

